spring:
  application:
    name: ROW-backend #项目名称
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/row
    username: root
    password: Cr@123456
server:
  port: 8080 #web后端端口

#持久层框架配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true